# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/python:2.7-stretch-node-browsers
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          working_directory: ~/repo/trigger-notify
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: 
          working_directory: ~/repo/trigger-notify
          command: yarn install
          name: yarn install
          

      - save_cache:
          working_directory: ~/repo/trigger-notify
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: 
          working_directory: ~/repo/trigger-notify
          command: yarn test
          name: yarn test

      - run: sudo npm install -g serverless
      - run: 
          working_directory: ~/repo/trigger-notify
          command: sls deploy
          name: sls deploy